"""remove date_latest_training from users table

Revision ID: 43da0c0c3f5e
Revises: ed7fb0017f7d
Create Date: 2020-09-08 12:38:51.526041

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "43da0c0c3f5e"  # pragma: allowlist secret
down_revision = "ed7fb0017f7d"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "date_latest_training")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "date_latest_training", sa.DATE(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
