"""add last_sent column to clins and pdf_last_sent to task_orders

Revision ID: 567bfb019a87
Revises: 0039308c6351
Create Date: 2020-01-31 14:06:21.926019

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '567bfb019a87' # pragma: allowlist secret
down_revision = '0039308c6351' # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clins', sa.Column('last_sent_at', sa.DateTime(), nullable=True))
    op.add_column('task_orders', sa.Column('pdf_last_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_orders', 'pdf_last_sent_at')
    op.drop_column('clins', 'last_sent_at')
    # ### end Alembic commands ###
