#!/bin/sh

# TODO: update this to rely on overlays for flexvol configuration

if [ -z "${K8S_CONTEXT+is_set}" ]; then
  K8S_CMD="kubectl"
else
  K8S_CMD="kubectl --context=$K8S_CONTEXT"
fi

if [ -z "${MIGRATION_TIMEOUT+is_set}" ]; then
  MIGRATION_TIMEOUT=120s
fi

if [ -z "${K8S_NAMESPACE+is_set}" ]; then
  K8S_NAMESPACE=atat
fi

# Expected settings. Script will error if these are not provided.
SETTINGS=(
  VMSS_CLIENT_ID
  KEYVAULT_NAME
  TENANT_ID
  CONTAINER_IMAGE
)

# Loop all expected settings. Track ones that are missing and build
# concatenated list for envsubst. If any are missing, exit.
MISSING_SETTINGS=()
for envvar in "${SETTINGS[@]}"; do
  if [ -z "${!envvar}" ]; then
    MISSING_SETTINGS+=(${envvar})
  fi
done

if [[ ${#MISSING_SETTINGS[@]} > 0 ]]; then
  >&2 echo "The following variables need to be set:"
  for missing in "${MISSING_SETTINGS[@]}"; do
    >&2 echo $missing
  done
  exit 1
fi

echo "Creating job..."
envsubst < deploy/shared/migration.yaml | $K8S_CMD -n ${K8S_NAMESPACE} apply -f -

echo "Wait for job to finish or timeout..."
JOB_SUCCESS=$(${K8S_CMD} -n ${K8S_NAMESPACE} wait --for=condition=complete --timeout=${MIGRATION_TIMEOUT} job/migration)

delete_job () {
  echo "Deleting job..."
  $K8S_CMD -n ${K8S_NAMESPACE} delete job migration
}

if echo "$JOB_SUCCESS" | grep -q "condition met"; then
  echo "Job ran successfully."
  delete_job
  exit 0
else
  POD_NAME=$(${K8S_CMD} -n ${K8S_NAMESPACE} get pods -l job-name=migration -o=jsonpath='{.items[0].metadata.name}')
  echo "Job failed:"
  $K8S_CMD -n ${K8S_NAMESPACE} logs $POD_NAME
  delete_job
  exit 1
fi
