#!/bin/bash

# script/dev_queue: Run the queue with entr if available

set -e

WORKER="poetry run celery -A celery_worker.celery worker --loglevel=INFO -B -c 1"

if [[ `command -v entr` ]]; then
  find atat | entr -r $WORKER
else
  $WORKER
fi
