#!/bin/bash

# script/sonarqube: Scan code base with sonarQube.

# script variables
SONAR_SCANNER_IMAGE="sonarsource/sonar-scanner-cli:4.5"

# exit when any command fails
set -e

# generate coverage reports
poetry run pytest --cov-report=xml
yarn jest --coverage

# repace local directory with container working directory
sed -i '' 's/\/.*\/atst/\/usr\/src/g' coverage.xml
sed -i '' 's/\/.*\/atst/\/usr\/src/g' coverage/lcov.info

# run SonarScanner using docker
docker run --rm \
    -e SONAR_TOKEN=$SONAR_TOKEN \
    -v $(pwd):/usr/src \
    $SONAR_SCANNER_IMAGE \
