#!/bin/bash

# script/sync-dod-certs: update the CA bundle with DOD intermediate and root CAs

CAS_FILE_NAME="Certificates_PKCS7_v5.6_DoD"
CA_CHAIN="ssl/server-certs/ca-chain.pem"

echo "Resetting CA bundle..."
rm $CA_CHAIN &> /dev/null || true
touch $CA_CHAIN

# dod intermediate certs
echo "Adding DoD root certs"
rm -rf tmp || true
mkdir tmp
curl --silent -o tmp/dod-cas.zip "https://dl.dod.cyber.mil/wp-content/uploads/pki-pke/zip/certificates_pkcs7_v5-6_dod.zip"
unzip tmp/dod-cas.zip -d tmp/ &> /dev/null
openssl pkcs7 -in "tmp/$CAS_FILE_NAME/$CAS_FILE_NAME.pem.p7b" -print_certs >> $CA_CHAIN
rm -rf tmp
