#!/bin/sh

if [ -z "${CSP:+is_set}" ]; then
  CSP=mock
fi

if [ -z "${AZURE_ACCOUNT_NAME:+is_set}" ]; then
  AZURE_ACCOUNT_NAME=atat
fi

if [ $CSP = "aws" ]; then
  echo "CLOUD_PROVIDER=aws" > .env
elif [ $CSP = "azure" ]; then
  cat << EOF > .env
CLOUD_PROVIDER=azure
AZURE_ACCOUNT_NAME=${AZURE_ACCOUNT_NAME}
AZURE_CONTAINER_NAME=task-order-pdfs
EOF
else
  echo "CLOUD_PROVIDER=mock" > .env
fi
